name: Build & Containerize Java Project

on: 
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: true
        type: number
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      
jobs:
  jib:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        distribution: 'adopt'
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        registry-type: public

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Run JIB and Push to Repository
      run: ./gradlew jib
        